project 'Umzugscoach.xcodeproj'
platform :ios, '10.0'

target 'Umzugscoach' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Umzugscoach
  # keyboard avoiding manager
  pod 'IQKeyboardManagerSwift'
end
